# Generated by Django 3.1 on 2020-08-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ob',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ob',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
